server {
    listen 8004;
    server_name 180.57.171.75;  # change this to your desired domain or subdomain

    location / {
        proxy_pass http://localhost:15672;  # assuming RabbitMQ Management is running on the default port
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
