# Adjust paths to your environment

proxy_cache_path /src/quantz-web/web-server/nginx/cache levels=1 keys_zone=imagecache:4M inactive=7d max_size=100M;

upstream service_uwsgi {
  server unix:/tmp/uwsgi.sock;
}

# cache server (will deprecated)
server {
  listen 8002;
  server_name 192.168.1.11;  # Set this to your server's IP or domain name
  charset utf-8;

  rewrite_log on;

  client_max_body_size 75M;
  sendfile on;

  location /resources/ {
    proxy_pass http://192.168.1.11:8000;  # Set this to your server's IP or domain name
    proxy_cache imagecache;
    proxy_cache_key $scheme$host$uri$arg_width$arg_height$arg_type$arg_quality$arg_time;
    proxy_cache_valid 200 1d;
    proxy_cache_valid 404 403 1m;
  }

  location / {
    include uwsgi_params;
    proxy_pass http://192.168.1.11:8000;  # Set this to your server's IP or domain name
  }
}

# quantz web server
server {
  listen 8000;
  server_name quantz.thinkxinc.com jessicas.online;

  charset utf-8;
  client_max_body_size 75M;
  sendfile on;

  location / {
    include uwsgi_params;
    uwsgi_pass unix:/tmp/uwsgi_quantz.sock;  # Unique socket for the quantz web server
  }

  # Static files for quantz web server
  location = /favicon.ico {
    alias /src/quantz-web/web-server/favicon.ico;
  }
  location = /robots.txt {
    alias /src/quantz-web/web-server/robots.txt;
  }
  location /sitemap.xml {
      rewrite ^/(.*)/$ /$1 permanent;  # Redirects with a 301 to remove the trailing slash
      alias /src/quantz-web/web-server/sitemap.xml;
  }
  location /img/ {
    root /src/quantz-web/web-server/views/;
  }
  location /js/ {
    root /src/quantz-web/web-server/views/;
  }
  location /css/ {
    root /src/quantz-web/web-server/views/;
  }
  location /video/ {
    root /src/quantz-web/web-server/views/;
  }
  location /audio/ {
    root /src/quantz-web/web-server/views/;
  }
  location /fonts/ {
    root /src/quantz-web/web-server/views/;
  }
  location /node_modules/ {
    root /src/quantz-web/web-server/views/;
  }
  location /web-client/ {
    root /src/quantz-web/;
  }
}
