# config/config.yml
host: "0.0.0.0" #"localhost"
port: 8009
upload_url: "/fs/upload"
access_url: "/fs/files/"
files_root_path: "/disk1/quantz"
limit_mb: 100
webhook_url: "https://quantz.thinkxinc.com/webhook/fileserver"
